name: WorstAukcionSuperMegaUltimate
version: '${version}'
main: WorstAukcionSuperMegaUltimate
api-version: '1.21'
depend:
  - Vault
commands:
  ah:
    description: Main auction command
    usage: /ah
